export const SHOW_FIRST_AD = 'SHOW_FIRST_AD';

export const SHOW_WAIT_AD = 'SHOW_WAIT_AD';

export const SHOW_FIRST_NAV = 'SHOW_FIRST_NAV';

export const REQUEST_GET_EXCHANGE_LIST = 'REQUEST_GET_EXCHANGE_LIST';

export const SUCCESS_GET_EXCHANGE_LIST = 'SUCCESS_GET_EXCHANGE_LIST';

export const ERROR_GET_EXCHANGE_LIST = 'ERROR_GET_EXCHANGE_LIST';

export const REQUEST_CHANGE_EXCHANGE = 'REQUEST_CHANGE_EXCHANGE';

export const SUCCESS_CHANGE_EXCHANGE = 'SUCCESS_CHANGE_EXCHANGE';

export const ERROR_CHANGE_EXCHANGE = 'ERROR_CHANGE_EXCHANGE';

export const REQUEST_GET_COMMODITY_SERVERS = 'REQUEST_GET_COMMODITY_SERVERS';

export const SUCCESS_GET_COMMODITY_SERVERS = 'SUCCESS_GET_COMMODITY_SERVERS';

export const ERROR_GET_COMMODITY_SERVERS = 'ERROR_GET_COMMODITY_SERVERS';

export const REQUEST_GET_ONE_EXCHANGE_INFO = 'REQUEST_GET_ONE_EXCHANGE_INFO';

export const SUCCESS_GET_ONE_EXCHANGE_INFO = 'SUCCESS_GET_ONE_EXCHANGE_INFO';

export const ERROR_GET_ONE_EXCHANGE_INFO = 'ERROR_GET_ONE_EXCHANGE_INFO';

export const REQUEST_CHANGE_COMMODITY = 'REQUEST_CHANGE_COMMODITY';

export const SUCCESS_CHANGE_COMMODITY = 'SUCCESS_CHANGE_COMMODITY';

export const ERROR_CHANGE_COMMODITY = 'ERROR_CHANGE_COMMODITY';

export const REQUEST_GET_QUOTES = 'REQUEST_GET_QUOTES';

export const SUCCESS_GET_QUOTES = 'SUCCESS_GET_QUOTES';

export const ERROR_GET_QUOTES = 'ERROR_GET_QUOTES';

export const REQUEST_GET_USER_COMMODITY_DATA = 'REQUEST_GET_USER_COMMODITY_DATA';

export const SUCCESS_GET_USER_COMMODITY_DATA = 'SUCCESS_GET_USER_COMMODITY_DATA';

export const ERROR_GET_USER_COMMODITY_DATA = 'ERROR_GET_USER_COMMODITY_DATA';

export const REQUEST_SYSTEM_INFO = 'REQUEST_SYSTEM_INFO';

export const SUCCESS_SYSTEM_INFO = 'SUCCESS_SYSTEM_INFO';

export const ERROR_SYSTEM_INFO = 'ERROR_SYSTEM_INFO';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';

export const RESET_USER_DATA = 'RESET_USER_DATA';

export const ERROR_LOGIN = 'ERROR_LOGIN';

export const REQUEST_REG = 'REQUEST_REG';

export const SUCCESS_REG = 'SUCCESS_REG';

export const ERROR_REG = 'ERROR_REG';

export const REQUEST_RESET = 'REQUEST_RESET';

export const SUCCESS_RESET = 'SUCCESS_RESET';

export const ERROR_RESET = 'ERROR_RESET';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';

export const ERROR_LOGOUT = 'ERROR_LOGOUT';

export const CHANGE_SYSTEM_TYPE = 'CHANGE_SYSTEM_TYPE';

export const CHANGE_COMMODITY_ID = 'CHANGE_COMMODITY_ID';

export const GET_APP_NAME = Symbol();

export const DOWN_LOAD_URL = Symbol();
// 检查是否注册
export const REQUEST_QUERY_REGIST_INFO = 'REQUEST_QUERY_REGIST_INFO';

export const SUCCESS_QUERY_REGIST_INFO = 'SUCCESS_QUERY_REGIST_INFO';

export const ERROR_QUERY_REGIST_INFO = 'ERROR_QUERY_REGIST_INFO';

// 查询交易所会员机构
export const REQUEST_GET_MEMBER_LIST = 'REQUEST_GET_MEMBER_LIST';

export const SUCCESS_GET_MEMBER_LIST = 'SUCCESS_GET_MEMBER_LIST';

export const ERROR_GET_MEMBER_LIST = 'ERROR_GET_MEMBER_LIST';

// 下单，建仓
export const REQUEST_CREATE_USER_ORDER = 'CREATE_USER_ORDER';

export const SUCCESS_CREATE_USER_ORDER = 'SUCCESS_CREATE_USER_ORDER';

export const ERROR_CREATE_USER_ORDER = 'ERROR_CREATE_USER_ORDER';

// 查询用户信息
export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';

export const SUCCESS_GET_USERS = 'SUCCESS_GET_USERS';

export const ERROR_GET_USERS = 'ERROR_GET_USERS';

// 查询机构信息
export const REQUEST_GET_ORGS = 'REQUEST_GET_ORGS';

export const SUCCESS_GET_ORGS = 'SUCCESS_GET_ORGS';

export const ERROR_GET_ORGS = 'ERROR_GET_ORGS';

// 修改用户
export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';

export const SUCCESS_UPDATE_USER = 'SUCCESS_UPDATE_USER';

export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';

// 查询用户
export const REQUEST_FIND_USER = 'REQUEST_FIND_USER';

export const SUCCESS_FIND_USER = 'SUCCESS_FIND_USER';

export const ERROR_FIND_USER = 'ERROR_FIND_USER';

// 获取系统配置
export const REQUEST_GET_SYS_CONFIG = 'REQUEST_GET_SYS_CONFIG';

export const SUCCESS_GET_SYS_CONFIG = 'SUCCESS_GET_SYS_CONFIG';

export const ERROR_GET_SYS_CONFIG = 'ERROR_GET_SYS_CONFIG';

// 获取用户数据
export const REQUEST_GET_USE_DATA = 'REQUEST_GET_USE_DATA';

export const SUCCESS_GET_USE_DATA = 'SUCCESS_GET_USE_DATA';

export const ERROR_GET_USE_DATA = 'ERROR_GET_USE_DATA';

// 查询客户交易记录
export const REQUEST_GET_TRADE_RECORD_PAGE = 'REQUEST_GET_TRADE_RECORD_PAGE';

export const SUCCESS_GET_TRADE_RECORD_PAGE = 'SUCCESS_GET_TRADE_RECORD_PAGE';

export const ERROR_GET_TRADE_RECORD_PAGE = 'ERROR_GET_TRADE_RECORD_PAGE';

// 忘记密码
export const REQUEST_FORGET_PWD = 'REQUEST_FORGET_PWD';

export const SUCCESS_FORGET_PWD = 'SUCCESS_FORGET_PWD';

export const ERROR_FORGET_PWD = 'ERROR_FORGET_PWD';

// 发送验证码
export const REQUEST_SEND_CAPTCHA = 'REQUEST_SEND_CAPTCHA';

export const SUCCESS_SEND_CAPTCHA = 'SUCCESS_SEND_CAPTCHA';

export const ERROR_SEND_CAPTCHA = 'ERROR_SEND_CAPTCHA';

// 设置、修改交易密码
export const REQUEST_UPDATE_PWD = 'REQUEST_UPDATE_PWD';

export const SUCCESS_UPDATE_PWD = 'SUCCESS_UPDATE_PWD';

export const ERROR_UPDATE_PWD = 'ERROR_UPDATE_PWD';

// 修改手机密码
export const REQUEST_UPDATE_MOBILE = 'REQUEST_UPDATE_MOBILE';

export const SUCCESS_UPDATE_MOBILE = 'SUCCESS_UPDATE_MOBILE';

export const ERROR_UPDATE_MOBILE = 'ERROR_UPDATE_MOBILE';

// 获取商品、服务器信息
export const REQUEST_GET_MERCHS_AND_SERVERS = 'REQUEST_GET_MERCHS_AND_SERVERS';

export const SUCCESS_GET_MERCHS_AND_SERVERS = 'SUCCESS_GET_MERCHS_AND_SERVERS';

export const ERROR_GET_MERCHS_AND_SERVERS = 'ERROR_GET_MERCHS_AND_SERVERS';

// 客户持仓记录（点微宝）
export const REQUEST_GET_TRADE_HOLD_HISPAGE = 'REQUEST_GET_TRADE_HOLD_HISPAGE';

export const SUCCESS_GET_TRADE_HOLD_HISPAGE = 'SUCCESS_GET_TRADE_HOLD_HISPAGE';

export const ERROR_GET_TRADE_HOLD_HISPAGE = 'ERROR_GET_TRADE_HOLD_HISPAGE';

// 操盘记录（点微宝）
export const REQUEST_USER_OPERS_PAGE = 'REQUEST_USER_OPERS_PAGE';

export const SUCCESS_USER_OPERS_PAGE = 'SUCCESS_USER_OPERS_PAGE';

export const ERROR_USER_OPERS_PAGE = 'ERROR_USER_OPERS_PAGE';

// 账户金币-金币记录（点微宝）
export const REQUEST_USER_TICKET_PAGE = 'REQUEST_USER_TICKET_PAGE';

export const SUCCESS_USER_TICKET_PAGE = 'SUCCESS_USER_TICKET_PAGE';

export const ERROR_USER_TICKET_PAGE = 'ERROR_USER_TICKET_PAGE';

// 账户金币-有效期（点微宝）
export const REQUEST_USER_TICKET_INFO_PAGE = 'REQUEST_USER_TICKET_INFO_PAGE';

export const SUCCESS_USER_TICKET_INFO_PAGE = 'SUCCESS_USER_TICKET_INFO_PAGE';

export const ERROR_USER_TICKET_INFO_PAGE = 'ERROR_USER_TICKET_INFO_PAGE';

// 首单补偿-信息（点微宝）
export const REQUEST_USER_FIRST_ORDER = 'REQUEST_USER_FIRST_ORDER';

export const SUCCESS_USER_FIRST_ORDER = 'SUCCESS_USER_FIRST_ORDER';

export const ERROR_USER_FIRST_ORDER = 'ERROR_USER_FIRST_ORDER';

// 首单补偿-金币领取、执行补偿（点微宝）
export const REQUEST_COMPENSATE_TICKET = 'REQUEST_COMPENSATE_TICKET';

export const SUCCESS_COMPENSATE_TICKET = 'SUCCESS_COMPENSATE_TICKET';

export const ERROR_COMPENSATE_TICKET = 'ERROR_COMPENSATE_TICKET';

// 登录
export const LOGIN_SUCCESS = Symbol();

// 资产推送
export const REQUEST_QUERY_USER_INFO_GATEWAY = 'REQUEST_QUERY_USER_INFO_GATEWAY';

export const SUCCESS_QUERY_USER_INFO_GATEWAY = 'SUCCESS_QUERY_USER_INFO_GATEWAY';

export const ERROR_QUERY_USER_INFO_GATEWAY = 'ERROR_QUERY_USER_INFO_GATEWAY';

// 获取支付中心地址
export const SUCCESS_DIRECT = 'SUCCESS_DIRECT';
