export const REQUEST_EXCHANGE_LIST = 'REQUEST_EXCHANGE_LIST';

export const SUCCESS_EXCHANGE_LIST = 'SUCCESS_EXCHANGE_LIST';

export const ERROR_EXCHANGE_LIST = 'ERROR_EXCHANGE_LIST';

export const REQUEST_CHANGE_EXCHANGE = 'REQUEST_CHANGE_EXCHANGE';

export const SUCCESS_CHANGE_EXCHANGE = 'SUCCESS_CHANGE_EXCHANGE';

export const ERROR_CHANGE_EXCHANGE = 'ERROR_CHANGE_EXCHANGE';

export const REQUEST_EXCHANGE_INFO = 'REQUEST_EXCHANGE_INFO';

export const SUCCESS_EXCHANGE_INFO = 'SUCCESS_EXCHANGE_INFO';

export const ERROR_EXCHANGE_INFO = 'ERROR_EXCHANGE_INFO';


export const REQUEST_SYSTEM_INFO = 'REQUEST_SYSTEM_INFO';

export const SUCCESS_SYSTEM_INFO = 'SUCCESS_SYSTEM_INFO';

export const ERROR_SYSTEM_INFO = 'ERROR_SYSTEM_INFO';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';

export const ERROR_LOGIN = 'ERROR_LOGIN';

export const REQUEST_REG = 'REQUEST_REG';

export const SUCCESS_REG = 'SUCCESS_REG';

export const ERROR_REG = 'ERROR_REG';

export const REQUEST_RESET = 'REQUEST_RESET';

export const SUCCESS_RESET = 'SUCCESS_RESET';

export const ERROR_RESET = 'ERROR_RESET';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';

export const ERROR_LOGOUT = 'ERROR_LOGOUT';

export const REQUEST_CHANGE_SYSTEM = 'REQUEST_CHANGE_SYSTEM';

export const SUCCESS_CHANGE_SYSTEM = 'SUCCESS_CHANGE_SYSTEM';

export const ERROR_CHANGE_SYSTEM = 'ERROR_CHANGE_SYSTEM';
